### ISSUE TITLE
Enterprise assistant handles CSRs sent by RPC-go during -local TLS configuration and IEEE 802.1x configuration

### ISSUE THREAD

**Issue by mechris1** [open-amt-cloud-toolkit/enterprise-assistant#9]
As an enterprise customer utilizing RPC-Go -local configuration flows, I would like to have RPC-Go fetch the TLS and 802.1x certificates from Enterprise Assistant during a local configuration. I desire the Enterprise Assistant to respond to CSR requests from RPC-Go during AMT Configuration.

**Acceptance Criteria:**

***EA Tasks:***
- [x] Enterprise Assistant can be configured to handle requests from RPS or RPC-GO
- [x] Enterprise Assistant must facilitate servicing RPC-Go CSRs for both TLS and IEEE 802.1x requests
- [x] Enterprise Assistant should validate the API Key or Token passed by RPC-GO
- [ ] Enterprise Assistant should only accept TLS session from RPC-GO

***RPC-GO Tasks:***
- [x]  RPC-Go must be configured to send CSRs to EA when performing TLS AMT configuration
- [x]  When performing AMT TLS configuration locally, RPC-GO should successfully obtain certificates from EA without requiring manual intervention (dependent on what is decided for EA)
- [x] Based on the findings from spike, give option to pass token or API Key via config.yaml and a flag

***Validation Tasks:***
- [x] Sensitive certificate and password information should not be exposed during the AMT Configuration process
- [x] Verification tests must validate that the certificate retrieval process is functioning securely and as intended

**Comment by graikhel-intel** [comment]
Added a new spike to track this task `Enterprise Assistant should only accept TLS session from RPC-GO` - https://github.com/orgs/open-amt-cloud-toolkit/projects/10/views/2?pane=issue&itemId=60388411
